MP-840/MP-1097
Nictiz/HL7-mappings pull request #222
Opened 2023-10-31 17:06 UTC by LuudSlagter

2023-11-01 07:43 UTC, weteringac reviewed
Heeft deze wijziging ook effect op fhir_2_ada?

2023-11-08 16:09 UTC, LuudSlagter commented on fhir_2_ada-r4/mp/9.3.0/payload/2.0.0-beta.2/all_profiles.xsl
> +    <xsl:import href="mp-AdministrationAgreement.xsl"/>
This won't work properly: all imports (except of the MedicationUse2 one) should refer to the stylesheet in the 2.0.0-beta.1 folder (see ada2fhir for an example on this).

2023-12-21 18:29 UTC, weteringac requested changes

2023-12-21 18:29 UTC, weteringac commented on ada_2_fhir-r4/mp/9.3.0/payload/2.0.0-beta.2/mp-MedicationUse2.xsl
Dit is een nieuw toegevoegde xsl voor dit wijzigingsverzoek, maar tov de beta.1 zie ik ook een wijziging bij relatie_episode when there is no relatie_contact, dat zit niet in de scope van dit wijzigingsverzoek denk ik? Hoe komt dat? Hetzelfde (extra) verschil is er ook tov de master branche, dus daar komt -ie niet vandaan.

Om redenen van backward compatibility (stel dat er een instance komt met codes van pre-MP93) vind ik het wel goed als de mapping dat juist vertaalt. Wij kennen immers de vorige versies. 

Suggestie daarom op regel 124:
                           <xsl:when test="(medicatie_gebruik_stop_type | medicatiegebruik_stop_type)[@code = $stoptypeMap[@stoptype = ('onderbroken', 'tijdelijk')]/@code]">on-hold</xsl:when>
                            <xsl:when test="(medicatie_gebruik_stop_type | medicatiegebruik_stop_type)[@code = $stoptypeMap[@stoptype = ('stopgezet','definitief')]/@code]">stopped</xsl:when>
                            
Verder op regel 126, check voor attribuut @code en géén @codeSystem =  nullFlavor, want als die er niet zijn is er feitelijk ook geen stoptype. Dus zoiets:
         <xsl:when test="gebruik_indicator/@value = 'false' and not((medicatie_gebruik_stop_type | medicatiegebruik_stop_type)[@code][not(@codeSystem = $oidHL7NullFlavor]])">not-taken</xsl:when>

2023-12-21 18:29 UTC, weteringac commented on fhir_2_ada-r4/mp/9.3.0/payload/2.0.0-beta.2/mp-MedicationUse2.xsl
als status in FHIR 'stopped' is, waarom zou je dan niet op stoptype mappen?
zelfde vraag voor 'on-hold'. 
Bij medicatiegebruik lijkt me dat semantisch gezien terecht, ook al is men vergeten de extensie stoptype mee te sturen.

2024-01-18 14:53 UTC, weteringac approved these changes

2024-01-19 13:47 UTC, merged