Removal of all fhir_2_ada scripts and related files
Nictiz/HL7-mappings pull request #237
Opened 2023-12-14 09:23 UTC by xatapult

This PR removes all scripts (XSLT, Ant) from the HL7-mappings `fhir_2_ada` component. The processing of this is taken over by the YATC component `fhir-2-ada`.

2023-12-14 14:38 UTC, weteringac requested changes
fhir-2-ada-r4 no longer works, because it depends on xsl's in fhir-2-ada

2023-12-14 15:36 UTC, helmavdl requested changes
I accept Arianne's comment as I use the same XSLTs

2024-01-09 12:37 UTC, xatapult commented
Ik heb een automatische dependency analyse geschreven en (voorzover ik zien) de enige stylesheet die door andere componenten gebruikt wordt weer teruggezet (`fhir_2_ada/fhir/fhir_2_ada_fhir_include.xsl`).

Mag ik nogmaals om een goedkeuring van deze PR verzoeken?

2024-01-11 09:52 UTC, weteringac approved these changes
Regression tested yatc fhir-2-ada and ant fhir-2-ada-r4. Both are fine.

2024-01-11 10:35 UTC, merged