NICTIZ-5183-12434-13379: Ada2fhir CiO 2.0.0-beta.2
Nictiz/HL7-mappings pull request #260
Opened 2024-03-11 11:04 UTC by LuudSlagter

2024-03-18 13:33 UTC, weteringac requested changes

2024-03-18 13:39 UTC, weteringac requested changes

2024-03-18 13:39 UTC, weteringac commented on ada_2_fhir-r4/fhir/2_fhir_fhir_include.xsl
>          <nm:map ada="medicatie_contra_indicatie" resource="Flag" profile="nl-core-MedicationContraIndication"/>
Waarom geen mapping meer naar cio-MedicationContraIndication, die maak je nu toch juist?
En wat is de mapping naar nl-core-MedicationContraIndication, bestaat die überhaupt in zibs2020?

2024-03-18 14:50 UTC, weteringac commented on ada_2_fhir-r4/fhir/2_fhir_fhir_include.xsl
>          <nm:map ada="medicatie_contra_indicatie" resource="Flag" profile="nl-core-MedicationContraIndication"/>
Helder, dank!

2024-03-18 14:56 UTC, LuudSlagter commented on ada_2_fhir-r4/cio/2.0.0/payload/cio-Condition.xsl
Done!

2024-03-19 07:18 UTC, LuudSlagter commented on ada_2_fhir-r4/cio/2.0.0/payload/cio-Condition.xsl
Done!

2024-03-19 10:06 UTC, LuudSlagter commented on ada_2_fhir-r4/cio/2.0.0/payload/cio-Condition.xsl
Done!

2024-03-19 10:07 UTC, LuudSlagter commented on ada_2_fhir-r4/cio/2.0.0/payload/cio-Condition.xsl
Doorgevoerd door nl-core-HealthProfessional-Practitioner(Role). Voor nl-core-ContactPerson en nl-core-Patient (en eventueel andere nl-core-profielen) wordt dit op een later moment doorgevoerd (en dan meteen voor alle informatiestandaarden en de R4-profielen).

2024-03-19 11:47 UTC, weteringac approved these changes

2024-03-19 12:38 UTC, merged