Mp 1681
Nictiz/HL7-mappings pull request #297
Opened 2024-10-28 16:32 UTC by weteringac

MP-1681 describes the problem where timezone was not converted properly. Now tested the whole HL7v3-ada-FHIR train in all directions.

2024-10-29 10:59 UTC, ahenket requested changes
See comment at hl7_2_ada_hl7_include.xml

2024-10-29 10:59 UTC, ahenket commented on hl7_2_ada/hl7/hl7_2_ada_hl7_include.xsl
Line 145 could be more efficient:
`replace($input-hl7-date, '^(\d+(\.\d+)?)([+-]\d{2,4})?$', '$1')`

Question: 20240101123456Z will fail to match in line 145 ... so if that should be supported you could use:
`replace($input-hl7-date, '^(\d+(\.\d+)?)(Z|[+-]\d{2,4})?$', '$1')`

Line 226 will never yield true as $str-date is an xs:date
`<xsl:when test="$str_date castable as xs:dateTime">`

Suggest to check for 
  `$str-datetime castable as xs:dateTime`
and then for
  `$str_date castable as xs:date`

2024-10-29 14:39 UTC, weteringac commented on hl7_2_ada/hl7/hl7_2_ada_hl7_include.xsl
20240101123456Z is officially not allowed in HL7v3 datetype TS, however the XSLT will now convert it properly when encountered (although it will also log a warning).
processed the other comments as suggested
added additional processing to prevent pseudo changes for our internal stuff

2024-10-31 09:25 UTC, ahenket approved these changes

2024-10-31 09:33 UTC, merged